<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <OutputPath>Build/</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <DebugType>full</DebugType>
    <GenerateDependencyFile>false</GenerateDependencyFile>
  </PropertyGroup>

  <ItemGroup>
    <Reference Update="@(Reference)">
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Dependencies/*.dll">
      <Private>False</Private>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Resources/src/**" />
    <Compile Remove="Dependencies/**" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources/assets-win.bundle">
    </EmbeddedResource>
    <EmbeddedResource Include="Resources/assets-mac.bundle">
    </EmbeddedResource>
    <EmbeddedResource Include="Resources/assets-linux.bundle">
    </EmbeddedResource>
  </ItemGroup>

  <Target Name="RemoveDependencies" AfterTargets="Build">
    <ItemGroup>
      <FilesToDelete Include="$(OutputPath)*.dll" Exclude="$(OutputPath)$(AssemblyName).dll" />
    </ItemGroup>
    <Delete Files="@(FilesToDelete)" />
  </Target>
</Project>
